name: Check Spelling
on:
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Pull pipelinecomponents/markdown-spellcheck Image
        run: docker pull pipelinecomponents/markdown-spellcheck
      - name: Spellcheck Markdown Files
        run: docker run --rm -i -v "$PWD:/github/workspace" --workdir /github/workspace -e FORCE_COLOR=1 pipelinecomponents/markdown-spellcheck --report "**/*.md" -n -a
